### ISSUE TITLE
lineup_status.json: Exception: Unexpected char '<' at 1:1 (JSON::ParseException)

### ISSUE THREAD

**Issue by Starbix** [TheJF/antennas#12]
I can't add antennas to Plex DVR, I get this error: 
<img width="616" alt="bildschirmfoto 2018-01-03 um 16 11 57" src="https://user-images.githubusercontent.com/12443257/34525925-e9097162-f0a0-11e7-8a03-e24632037449.png">
And in the log of the docker container I get this:
```
8-01-03 16:02:07 +0100 200 GET /lineup_status.json 47.4µs
2018-01-03 16:02:07 +0100 200 GET /discover.json 53.4µs
2018-01-03 16:02:07 +0100 200 GET /lineup_status.json 40.7µs
2018-01-03 16:02:11 +0100 200 GET /discover.json 79.3µs
2018-01-03 16:02:11 +0100 200 GET /lineup_status.json 33.3µs
2018-01-03 16:02:11 +0100 200 GET /discover.json 47.8µs
2018-01-03 16:02:11 +0100 200 GET /lineup_status.json 37.1µs
Exception: Unexpected char '<' at 1:1 (JSON::ParseException)
0x4ec23e: ??? at ??
0x4f1dc9: ??? at ??
0x4f1da4: ??? at ??
0x4eaba3: ??? at ??
0x4ca7aa: ??? at ??
0x53bbd0: ??? at ??
0x52ed0b: ??? at ??
0x52d6b1: ??? at ??
0x5387ca: ??? at ??
0x5360fb: ??? at ??
0x53b0da: ??? at ??
0x5228bd: ??? at ??
0x4177d8: ??? at ??
0x0: ??? at ??

2018-01-03 16:02:12 +0100 500 GET /lineup.json 1.76ms
2018-01-03 16:03:12 +0100 404 POST /lineup.post?scan=start&source=Cable 102.3µs
2018-01-03 16:03:12 +0100 404 POST /lineup.post?scan=start&source=Cable 103.5µs
2018-01-03 16:03:13 +0100 404 POST /lineup.post?scan=start&source=Cable 68.7µs
2018-01-03 16:06:44 +0100 404 POST /lineup.post?scan=start&source=Cable 101.7µs
2018-01-03 16:06:44 +0100 404 POST /lineup.post?scan=start&source=Cable 116.0µs
2018-01-03 16:06:45 +0100 404 POST /lineup.post?scan=start&source=Cable 414.4µs
2018-01-03 16:06:45 +0100 404 POST /lineup.post?scan=start&source=Cable 65.4µs
```
Headend version: HTS Tvheadend 4.3-861~g715a4a844

**Comment by TheJF** [comment]
Hm, it looks like the `TVHEADEND_URL` isn't properly set. Make sure that is the right address with the right username and password.

If that still doesn't work, can you post the config settings that you see when you navigate to the Antennas page? (you can type them in to obscure your username and password)

**Comment by Starbix** [comment]
<img width="538" alt="bildschirmfoto 2018-01-03 um 17 40 52" src="https://user-images.githubusercontent.com/12443257/34529748-49d22adc-f0ad-11e7-962b-b8ccf6ca806b.png">

**Comment by TheJF** [comment]
Thank you, the config looks pretty good. I'll see if I can reproduce on my side.

**Comment by Codehhh** [comment]
I am getting this error as well.

**Comment by TheJF** [comment]
Okay, this could be that Antennas couldn't talk to Tvheadend (because TVH was down, or its port wasn't exposed, or the IP is wrong, or for any number of reason), or that there was an error in the username/password.

I've added a few things to help troubleshoot the problem here, which is in the new version of the Antennas:
1. There's now a "Status" line that will explain what Antennas is having a problem with,
2. In the logs, when it crashes, it will now also output what it got from Tvheadend, if anything, along with potential solutions.

Let me know how that goes for both of you!

**Comment by TheJF** [comment]
The status will look a bit like this (as an example if it saying it couldn't authenticate)

![image](https://user-images.githubusercontent.com/999846/34637142-14a07928-f264-11e7-98ba-69cd2f99ee4a.png)

**Comment by Starbix** [comment]
Thank you. With the status I was able to easily troubleshoot it. I believe it was a tvheadend problem.

But now I got a new problem: 
<img width="700" alt="" src="https://user-images.githubusercontent.com/12443257/34640551-b9655f56-f2f4-11e7-9288-f826251f962e.png">
It's probably not a antennas problem, so I'm going to close this isse and thank you once more 😁

**Comment by Codehhh** [comment]
Thanks for the update, made it super easy to figure out the problem
