### ISSUE TITLE
Only one channel in Plex

### ISSUE THREAD

**Issue by processor83** [TheJF/antennas#15]
I have many channel in tvheadend but when i add Antennas tuner in Plex it only see 1 channel.

Any idea what cause this??

**Comment by TheJF** [comment]
Not sure, I've definitely never heard of this issue before and it works fine for me.

What happens when you go to:
`http://user:pass@your-tvheadend-server/api/channel/grid?start=0&limit=999999`

Replacing `user:pass@your-tvheadend-server` with your Tvheadend server information?

**Comment by processor83** [comment]
I found it all my channel from m3u dont have channel number they all have channel 0 so only one channel 0 is seen by plex!

**Comment by daniel-loader** [comment]
Did you find a solution to quickly map channel numbers to iptv/m3u sources?

**Comment by tristan-k** [comment]
I think I might have the same issue. Can you explain in more detail how you fixed it. 

![Screenshot 2023-01-12 at 23-46-28 Plex](https://user-images.githubusercontent.com/732025/212199555-d729184c-c9d2-49b6-9310-35e45a9e9e06.png)
