### ISSUE TITLE
Plex not recognizing antennas

### ISSUE THREAD

**Issue by karlos1338** [TheJF/antennas#16]
Hi,

I am using Plex Version 1.11.0.4666 (Ubuntu, 64bit) and tvheadend 4.3-991~g9718e8e.

I started antennas using:
`sudo docker run -p 5004:5004 -e ANTENNAS_URL=http://192.168.0.44:5004 -e TVHEADEND_URL=http://admin:password@192.168.0.44:9981 thejf/antennas`

Status Page of antennas says "all system go". When adding the device to plex over web interface the device is not recognized, even when typing in 192.168.0.44:5004.

Plex Logfile:

```
Jan 20, 2018 10:28:49.310 [0x7fd9c0bff700] DEBUG - DVR:Device: Discovering and refreshing devices.
Jan 20, 2018 10:28:49.311 [0x7fd9c0bff700] DEBUG - DVR:Grabber: HDHomerun discovered 0 compatible devices.
Jan 20, 2018 10:28:49.311 [0x7fd9c0bff700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/12345670 at http://192.168.0.44:5004
Jan 20, 2018 10:28:49.311 [0x7fd9c0bff700] DEBUG - HTTP requesting GET http://192.168.0.44:5004/discover.json
Jan 20, 2018 10:28:49.312 [0x7fd9c0bff700] DEBUG - HTTP 200 response from GET http://192.168.0.44:5004/discover.json
Jan 20, 2018 10:28:49.313 [0x7fd9c0bff700] DEBUG - HTTP requesting GET http://192.168.0.44:5004/lineup_status.json
Jan 20, 2018 10:28:49.314 [0x7fd9c0bff700] DEBUG - HTTP 200 response from GET http://192.168.0.44:5004/lineup_status.json
Jan 20, 2018 10:28:49.319 [0x7fd9c0bff700] DEBUG - DVR:Device: Device was alive, refreshed device://tv.plex.grabbers.hdhomerun/12345670.
Jan 20, 2018 10:28:49.319 [0x7fd9c0bff700] DEBUG - DVR:Grabber: Mystery discovered 0 compatible devices.
Jan 20, 2018 10:28:56.102 [0x7fd9ae3fe700] DEBUG - DVR:Device: Testing grabber HDHomerun device device://tv.plex.grabbers.hdhomerun/12345670 at http://192.168.0.44:5004
Jan 20, 2018 10:28:56.107 [0x7fd9ae3fe700] DEBUG - DVR:Device: Device device://tv.plex.grabbers.hdhomerun/12345670 died
Jan 20, 2018 10:28:56.108 [0x7fd9ae3fe700] DEBUG - DVR:Grabber: Mystery discovered 0 compatible devices.
```
When I take a look on the network in chrome, I see the discover process of Plex. It returns a XML:

```
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="2">
<Device key="1" uuid="device://tv.plex.grabbers.tunerservice/dvb%23v4l%23%2fsys%2fdevices%2fpci0000%3a00%2f0000%3a00%3a01.0%2f0000%3a01%3a00.0%3a14f1%3a8880" uri="" protocol="livetv" status="alive" state="enabled" lastSeenAt="1516441352" make="Hauppauge" model="WinTV-quadHD" modelNumber="1607" source="1" sources="0,1,2" thumb="/:/resources/dvr/device-pcie-560.png" tuners="1">
<Setting id="transcodeDuringRecord" label="Convert video while recording" default="0" summary="[Experimental] This can save disk space and improve compatibility. Converting requires a fast CPU." type="int" value="0" hidden="0" advanced="0" group="" enumValues="0:Off|2:Transcode" />
</Device>
<Device key="2" uuid="device://tv.plex.grabbers.hdhomerun/12345670" uri="http://192.168.0.44:5004" protocol="livetv" status="dead" state="enabled" lastSeenAt="1516440529" canTranscode="1" deviceAuth="test1234" make="Silicondust" model="Antennas" modelNumber="HDTC-2US" source="1" sources="1" thumb="/:/resources/dvr/device-generic-560.png" tuners="6">
<Setting id="transcodeProfile" label="Transcoder Quality" default="heavy" summary="The quality of the transcoding used when recording. Selecting original format may result in very large files." type="text" value="heavy" hidden="0" advanced="0" group="" enumValues="none:Original format|heavy:Highest quality|mobile:High quality (30fps limit)|internet540:Medium quality (540p)|internet480:Medium quality (480p)|internet360:Low quality (360p)|internet240:Low quality (240p)" />
</Device>
</MediaContainer>
```

I don't know what to do. Everything seems fine for me :(

**Comment by karlos1338** [comment]
One thing I noticed:
When restarting plex and opening the DVR process for the first time antennas is being recognized and shown. But removed after 3 seconds because it "died". I was able to click it fast enough and saw that plex found my channels. Unfortunately I can't finish the process because plex says that antenna "died".

**Comment by nexusle** [comment]
Same here. Tried it today for the first time, because the tvhProxy didn't work for me anymore in case of a too new python version.

**Comment by xorinzor** [comment]
Oddly enough, this happens to me too, and can be fixed by temporarely unplugging the HDHomeRun from  LAN until you completed all steps.

**Comment by TheJF** [comment]
Plex will show the device as dead, but it will still stream. I'd love to know what Plex is looking for to show dead or alive in the device list, but not having a HDHomeRun is making it hard to reverse-engineer that.

Or is it a case of it not streaming at all (especially when you _also_ have a HDHomeRun?)

**Comment by TheJF** [comment]
Problem identified, and currently working on a fix.

**Comment by xorinzor** [comment]
Care to tell us what's causing it? :)

**Comment by TheJF** [comment]
Actually, I haven't quite figured out the whole cause of the problem. I thought it was simply due to Plex using SSDP to discover, and Antennas not advertising with SSDP. So, I implemented SSDP on the server and it now advertises itself, but still it doesn't show up in Plex.

I now have a HDHomeRun and I'm looking at how it talks to Plex, trying to figure out what Plex wants for it to find Antennas and not think that it's dead, and I'm getting closer, but unfortunately, what I thought was the solution didn't seem to be the whole thing.

**Comment by HazCod** [comment]
Little side note from the telly project: is your SSDP implementation responding to M-HEAD requests from Plex?
Mine isn’t and I’m suspecting that’s the reason the device is marked as dead.

**Comment by TheJF** [comment]
@HazCod Hey! Sorry, just noticed this message. I believe it now shows up as alive with SSDP, and it seems you got yours working (and to find it automatically too :D ) so yay!

**Comment by TheJF** [comment]
Works in latest release, assuming Antennas is hosted correctly. Will attempt to make it easier for Antennas to be corrected in the future, but closing this for now.
