### ISSUE TITLE
Switch to digest auth for Tvheadend

### ISSUE THREAD

**Issue by TheJF** [TheJF/antennas#18]
Newer versions of Tvheadend use digest auth for requests. This breaks the way antennas is currently set up, and it needs to be upgraded for it to work.

**Comment by allanak** [comment]
I found this as well. As a workaround for now, you can configure TVH to accept basic auth under the General settings

**Comment by TheJF** [comment]
Oh, excellent, thanks @allanak! I've got a fix in the work that I just need to get back to when I get the time, but definitely very good workaround for people in the meantime.

**Comment by nbonfire** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/2932666/38334053-5781355c-3828-11e8-8ba6-d8c8eb3579dd.png">

@allanak 
I still get "Failed to authenticate with Tvheadend" after switching to basic auth. Is there another spot it needs to be changed? This was in config -> general -> base -> advanced. Alternately do you know when the change happened so I can roll back tvheadend?

**Comment by TheJF** [comment]
I'm getting much closer to this working. I have digest auth implemented on my new branch, and it connects and now lists all the channels.

One thing that you do have to do on the Tvheadend side though is to create a `*` user that has access to streams and nothing else (you can restrict it to your own internal network)

I'll put up instructions for this when I merge the changes in (which includes a complete rewrite of Antennas to Node), which will also include Antennas showing up automatically without having to manually type in the IP, using SSDP.

**Comment by TheJF** [comment]
Digest auth implemented and merged in 3.0.
