### ISSUE TITLE
compiler error

### ISSUE THREAD

**Issue by neidersun** [TheJF/antennas#19]
I can not compile a lockal compile

root@DESKTOP-RRP2TLA:/home/hts/antennas/antennas# crystal build ./src/antennas.cr
Error in src/antennas.cr:132: instantiating 'Kemal:Module#run(Int32)'

Kemal.run(5004)
      ^~~

in lib/kemal/src/kemal.cr:12: instantiating 'Kemal:Module#run(Int32)'

    self.run port do
         ^~~

in lib/kemal/src/kemal.cr:55: instantiating 'send_file(HTTP::Server::Context, String)'

          send_file env, file_path
          ^~~~~~~~~

in lib/kemal/src/kemal/helpers/helpers.cr:109: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:109: instantiating 'File:Class#open(String)'

  File.open(file_path) do |file|
       ^~~~

in lib/kemal/src/kemal/helpers/helpers.cr:120: 'Flate::Writer.new' is not expected to be invoked with a block, but a block was given

      Flate::Writer.new(env.response) do |deflate|
                    ^~~

root@DESKTOP-RRP2TLA:/home/hts/antennas/antennas#

**Comment by TheJF** [comment]
Try running `shards install`, and if that doesn't work, `shards update` and then `shards install`

**Comment by neidersun** [comment]
no success. please check
