### ISSUE TITLE
BaseURL, LineupURL read from config.yml?

### ISSUE THREAD

**Issue by mprajsler** [TheJF/antennas#2]
Hi,
can you please modify the code to read these two as a string from config?
BaseURL: "test",
LineupURL: "test"
Thanks and Regards,
M.

**Comment by TheJF** [comment]
Sure! I'll try to get on this shortly.

**Comment by mprajsler** [comment]
Hi, thank you take your time. I am using your docker container can you update the binary there aswell?
I think it should solve issue with message "device not found check that is turned on..." on newer plex server version but lets see if that helps.
Do you have this message on your config?
M.

**Comment by mprajsler** [comment]
Hi can you please incorporate latest fix in tvhproxy?

https://github.com/jkaberg/tvhProxy/pull/31

**Comment by TheJF** [comment]
@mprajsler PR created, can't test it at the moment, so will merge it after

**Comment by mprajsler** [comment]
Can you update docker image after? Thanks again

**Comment by TheJF** [comment]
Now fixed and updated! If you pull down the latest image, it should work. You can also configure it using environment variables now.

**Comment by mprajsler** [comment]
as with current coding we got BaseURL and LineupURL changed but it gets complete tvheadend url i.e. http://user:pass@192.168.0.1:9981 there where in fact we need just i.e. 192.168.0.1:5004
making extra variable should fix this and we will have it fully under controll

**Comment by mprajsler** [comment]
Hi made two PRs today please have a look thank you!
M.
