### ISSUE TITLE
Connected to tvheadend, but passes off urls without username/password?

### ISSUE THREAD

**Issue by ghostyroasty** [TheJF/antennas#28]
![ink](https://user-images.githubusercontent.com/3001424/42401931-ffdf8af8-8145-11e8-9604-4b59e4892bda.png)

I have the config setup correctly including the username and password that is set up in tvheadend. The attached photo is what shows on the lineup.json file when I load it via a web browser. If I open in vlc, it asks for username/password, and in Plex, the channel times out.

**Comment by TheJF** [comment]
Do you have an anonymous user configured in Tvheadend?

<img width="906" alt="screen shot 2018-07-06 at 3 54 56 pm" src="https://user-images.githubusercontent.com/999846/42403279-f95a9efe-8134-11e8-93bb-d5408a6f42a1.png">

**Comment by TheJF** [comment]
No reply, closing as likely configuration error of Tvheadend.
