### ISSUE TITLE
Autostart help

### ISSUE THREAD

**Issue by ikolsteren** [TheJF/antennas#33]
Trying to get antennas to work via autostart and have had no success.
I got it working by pm2 start index.js and web interface loaded and saw it in plex but it dies when adding the tuner and I need to reboot to get working again
It was a similar issue to when I ran as a daemon: node index.js >/dev/null 2>&1 &  
I figured it was my ssh session dying and causing the grief
It is a new setup and I have tvheadend working to the best of my knowledge and have had some success it working.

**Comment by ikolsteren** [comment]
Looks like when I run 
node index.js >/dev/null 2>&1 &
It works and then when I look at ps -x it goes right to Exit

**Comment by TheJF** [comment]
@ikolsteren What do the logs output?

**Comment by ikolsteren** [comment]
Where can I get the log for you? looking in my antennas folder and I don't see one
I have installed at /usr/lib/node_modules/antennas

**Comment by TheJF** [comment]
Try starting it without `>/dev/null 2>&1 &` (that directs the output of the command to `/dev/null` which means it's deleting it)

So just run:
`node index.js` and see what it says

**Comment by ikolsteren** [comment]
Mixed results when I run.   It was working the first time but when I rerun then no error and won’t find the tuner. 
/usr/lib/node_modules/antennas $ node index.js 
📡  Antennas are deployed! Proxying from http://192.168.86.33:5004
🕵️‍  Broadcasting to SSDP for discovery...
  <-- GET /lineup.json
  --> GET /lineup.json 200 189ms 10.09kb

It sat there when before would see more gets

**Comment by TheJF** [comment]
That looks like it's happy. When you navigate to http://192.168.86.33:5004 in your browser, do you get a web interface?

**Comment by ikolsteren** [comment]
I rebooted the box. 
Ran command and the tuner is seen in Plex and then dies before even picking the channels
pi@homebridge:/usr/lib/node_modules/antennas $ node index.js 
📡  Antennas are deployed! Proxying from http://192.168.86.33:5004
🕵️‍  Broadcasting to SSDP for discovery...
  <-- GET /discover.json
  --> GET /discover.json 200 69ms 389b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 4ms 77b
  <-- GET /device.xml
  --> GET /device.xml 200 146ms 2.44kb
  <-- GET /discover.json
  --> GET /discover.json 200 9ms 389b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 4ms 77b
  <-- GET /discover.json
  --> GET /discover.json 200 8ms 389b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 4ms 77b
  <-- GET /lineup.json
  --> GET /lineup.json 200 180ms 10.09kb
  <-- GET /device.xml
  --> GET /device.xml 200 43ms 2.44kb
  <-- GET /discover.json
  --> GET /discover.json 200 7ms 389b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 3ms 77b
  <-- GET /discover.json
  --> GET /discover.json 200 14ms 389b
  <-- GET /lineup_status.json
  --> GET /lineup_status.json 200 5ms 77b

**Comment by ikolsteren** [comment]
Yes get the interface. Not sure where it is dying as should be very simple.

**Comment by ikolsteren** [comment]
Web is still up but Plex doesn’t see it.  I have two different Plex servers and both the same thing
