### ISSUE TITLE
antennas not working 

### ISSUE THREAD

**Issue by ceramik** [TheJF/antennas#40]
i have install antennas docker image 

i run docker image and host connect 
but antennas can't working

this error log 

Antennas failed to connect to Tvheadend!
    Check that:
      - Tvheadend is running.
      - Antennas is correctly pointing to Tvheadend, on the right port.
      - That your username and login are correct. 

    Here's a dump of the error:
    RequestError: Error: connect EINVAL 0.0.0.1:80 - Local (0.0.0.0:0)

i don't no what problem 

answer me

thank you

**Comment by jfarseneau-wb** [comment]
You have to run Tvheadend, and set your TVHEADEND_URL to be pointing to the right address and port.

It looks like you're trying to connect to `0.0.0.1:80`, which is likely not where Tvheadend is running in your setup.

**Comment by TheJF** [comment]
You have to run Tvheadend, and set your TVHEADEND_URL to be pointing to the right address and port.

It looks like you're trying to connect to 0.0.0.1:80, which is likely not where Tvheadend is running in your setup.
